# Homework Assignment 13: Python Data Structures NumPy Arrays

In [1]:
import numpy as np
x = np.arange(12).reshape((3,4))

x.sum()

66

In [2]:
import numpy as np

x = np.arange(12).reshape((3,4))

x.sum(axis=0)

array([12, 15, 18, 21])

In [3]:
# An empty 1D array of Integers : shaped = 8

import numpy as np

np.empty(8, dtype=int)

array([   0,    1,    0,  692, 1256,    0,  768,  692])

In [4]:
# Am empaty 1D array of integers: shape ( a tuple )
import numpy as np

np.empty([2,3], dtype=int)

array([[189423280,       692,         0],
       [        0,         1,   4456526]])

In [5]:
# an 1D array as strings 
import numpy as np

np.empty(8, dtype=str)

array(['', '', '', '', '', '', '', ''], dtype='<U1')

In [6]:
import numpy as np

a = np.array([[1., 2., 3.],[4.,5.,6.]])

np.empty_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
import numpy as np

np.eye (8, k =2)

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
import numpy as np

np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
import numpy as np

np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
import numpy as np

np.ones(8, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
import numpy as np

np.full(8, 2)

array([2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
import numpy as np

np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [13]:
import numpy as np

np.arange(3, 19, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17])

In [14]:
import numpy as np

np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [15]:
import numpy as np

np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [16]:
import numpy as np

np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [17]:
import numpy as np

np.array([1, 2, 3, 4, 5], ndmin=2)

array([[1, 2, 3, 4, 5]])

In [18]:
import numpy as np

a = [1, 2, 3, 4, 5]

b = np.asarray([1, 2, 3, 4, 5])

c = np.asarray(a)

print (c)

[1 2 3 4 5]


In [19]:
import numpy as np

x = np.arange(9).reshape((3,3))

print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
import numpy as np

x = np.arange(9).reshape((3,3))

np.diag(x, k = 1)

array([1, 5])

In [21]:
# Homework Assignment 13: 